spring.application.name=java-backend-interview
server.port=8081
server.servlet.context-path=/absproxy/8081
server.forward-headers-strategy=framework

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb;webAllowOthers=true;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.settings.web-allow-others=true


# H2 Console (for development)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

